services:
  dc_voice_monitor:
    build: .
    image: dc_voice_monitor
    restart: unless-stopped
    container_name:  discord-tanga-bot
    env_file:
      - ./.env
    ports:
      - 8008:8080
    volumes:
      - ./assets/images/:/images/
      - ./config/:/app/config/
      - ./assets/models/:/app/vosk-model/
      - ./data/garmin-output/:/app/garmin-output/

