services:
  dc_voice_monitor:
    build: .
    image: dc_voice_monitor
    restart: unless-stopped
    container_name:  discord-tanga-bot
    env_file:
      - ./.env
    ports:
      - 8008:8080
    volumes:
      - ./images/:/images/
      - ./config/:/app/config/
      - ./vosk-model/:/app/vosk-model/
      - ./garmin-output/:/app/garmin-output/

